# Generated by Django 5.2.9 on 2026-08-25 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('mp_payment_id', ''), _negated=True), fields=('mp_payment_id',), name='uniq_payment_mp_payment_id'),
        ),
    ]
