# Generated by Django 5.2.17 on 2026-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_uniq_payment_mp_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='próxima cobrança'),
        ),
    ]
