# Generated by Django 5.2.9 on 2025-12-31 11:51

import django.core.validators
import django.db.models.deletion
import trades.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(verbose_name='executado em')),
                ('symbol', models.CharField(max_length=20, verbose_name='ticker')),
                ('market', models.CharField(choices=[('stocks', 'Ações'), ('indices', 'Índices'), ('dollar', 'Dólar'), ('crypto', 'Cripto'), ('forex', 'Forex')], max_length=20, verbose_name='mercado')),
                ('direction', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venda')], max_length=10, verbose_name='direção')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='quantidade')),
                ('high_time_frame', models.CharField(choices=[('5', '5 min'), ('15', '15 min'), ('60', '60 min'), ('240', '240 min')], max_length=3, verbose_name='HTF')),
                ('trend', models.CharField(choices=[('bullish', 'Alta'), ('bearish', 'Baixa'), ('range', 'Lateral')], max_length=10, verbose_name='tendência')),
                ('premium_discount', models.CharField(choices=[('sell_premium', 'Venda prêmio'), ('sell_discount', 'Venda desconto'), ('buy_premium', 'Compra prêmio'), ('buy_discount', 'Compra desconto')], max_length=20, verbose_name='prêmio/desconto')),
                ('region_htf', models.CharField(choices=[('primary', 'Primária'), ('secondary', 'Secundária'), ('none', 'N/D')], max_length=15, verbose_name='região HTF')),
                ('entry_type', models.CharField(choices=[('anticipated', 'Antecipado'), ('confirmed', 'Confirmado')], max_length=12, verbose_name='tipo de entrada')),
                ('setup', models.CharField(choices=[('flip', 'Flip'), ('choch', 'Choch'), ('liquidity', 'Liquidity'), ('pd', 'PD'), ('fvg', 'FVG'), ('top_failure', 'Falha de topo'), ('bottom_failure', 'Falha de fundo'), ('continuation', 'Continuação'), ('double_top', 'Topo duplo'), ('double_bottom', 'Fundo duplo'), ('none', 'N/D'), ('wedge', 'Cunha')], max_length=15, verbose_name='setup')),
                ('trigger', models.CharField(choices=[('region', 'Região'), ('passagem', 'Passagem'), ('martelo_bf', 'Martelo + BF'), ('fffd', 'FFFD'), ('padrao', 'Padrão'), ('none', 'N/D'), ('rocadinha', 'Roçadinha'), ('barra_ignorada', 'Barra ignorada'), ('gift', 'Gift')], max_length=20, verbose_name='gatilho')),
                ('target_price', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='alvo')),
                ('stop_price', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='stop')),
                ('partial_trade', models.CharField(choices=[('yes_pos', 'Sim +5x1'), ('no_done', 'Não fiz'), ('yes_neg', 'Sim -5x1'), ('not_available', 'Sem parcial')], max_length=20, verbose_name='parcial')),
                ('result_type', models.CharField(choices=[('gain', 'Gain'), ('loss', 'Loss'), ('break_even', 'Break even')], max_length=12, verbose_name='resultado')),
                ('currency', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro')], default='BRL', max_length=5, verbose_name='moeda')),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='resultado financeiro')),
                ('technical_gain', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='ganho técnico')),
                ('is_public', models.BooleanField(default=False, help_text='Permite mostrar esta operação no mural compartilhado.', verbose_name='exibir publicamente?')),
                ('display_as_anonymous', models.BooleanField(default=True, help_text="Se público, mostra o trader como 'Anônimo' nas visualizações.", verbose_name='exibir como anônimo?')),
                ('screenshot', models.ImageField(blank=True, help_text='Envie uma imagem PNG ou JPEG com até 5 MB.', upload_to='trades/screenshots/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), trades.validators.validate_image_file_size], verbose_name='captura')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trade',
                'verbose_name_plural': 'trades',
                'ordering': ('-executed_at', '-id'),
            },
        ),
    ]
