# Generated by Django 5.2.9 on 2026-01-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_smc_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entry_type',
            field=models.CharField(choices=[('anticipated', 'Antecipado'), ('confirmed', 'Confirmado'), ('lateral', 'Lateral')], max_length=12, verbose_name='tipo de entrada'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trend',
            field=models.CharField(choices=[('bullish', 'A favor'), ('range', 'Lateral'), ('bearish', 'Contra')], max_length=10, verbose_name='tendência'),
        ),
    ]
