# Generated by Django 5.2.9

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trades", "0006_alter_aianalyticsrun_result_alter_trade_screenshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalAIAnalyticsRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requested_at", models.DateTimeField(auto_now_add=True, verbose_name="solicitado em")),
                ("result", models.TextField(blank=True, verbose_name="resultado da análise")),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="global_ai_analytics_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "execução análise IA global",
                "verbose_name_plural": "execuções análise IA global",
                "ordering": ("-requested_at",),
            },
        ),
    ]
