# Generated by Django 5.2.9 on 2026-08-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_alter_trade_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalyticsrun',
            name='error_detail',
            field=models.TextField(blank=True, verbose_name='detalhe do erro'),
        ),
        migrations.AddField(
            model_name='aianalyticsrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('success', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=10, verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='globalaianalyticsrun',
            name='error_detail',
            field=models.TextField(blank=True, verbose_name='detalhe do erro'),
        ),
        migrations.AddField(
            model_name='globalaianalyticsrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('success', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=10, verbose_name='situação'),
        ),
    ]
