# Generated by Django 5.2.17 on 2026-08-25 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_backfill_ai_run_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', '-executed_at'], name='trade_user_executed_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['is_public', '-executed_at'], name='trade_public_executed_idx'),
        ),
    ]
