# Generated by Django 5.2.9 on 2025-12-30 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('document_id', models.CharField(blank=True, max_length=20, verbose_name='documento (CPF/CNPJ)')),
                ('country', models.CharField(default='BR', max_length=2, verbose_name='país')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='estado')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='complemento')),
                ('experience_level', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], default='beginner', max_length=20, verbose_name='nível de experiência')),
                ('primary_market', models.CharField(choices=[('stocks', 'Ações'), ('index_futures', 'Índice Futuro'), ('dollar_futures', 'Dólar Futuro'), ('crypto', 'Criptoativos'), ('other', 'Outros')], default='index_futures', max_length=20, verbose_name='mercado principal')),
                ('trading_style', models.CharField(choices=[('day_trade', 'Day Trade'), ('swing_trade', 'Swing Trade'), ('position', 'Position'), ('investor', 'Investidor')], default='day_trade', max_length=20, verbose_name='estilo de operação')),
                ('broker', models.CharField(blank=True, max_length=100, verbose_name='corretora')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='fuso horário')),
                ('email_opt_in', models.BooleanField(default=True, verbose_name='aceita receber e-mails?')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='aceitou os termos?')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
                ('privacy_accepted', models.BooleanField(default=False, verbose_name='aceitou política de privacidade?')),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceitado em')),
                ('referral_source', models.CharField(blank=True, max_length=100, verbose_name='como conheceu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
    ]
