# Generated by Django 5.2.9 on 2025-12-31 11:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='saldo atual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='saldo inicial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último reset'),
        ),
    ]
