# Generated by Django 5.2.17 on 2026-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_unique_discord_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='sessão atual'),
        ),
    ]
