# Generated by Django 5.2.9 on 2026-01-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('value_base', models.FloatField()),
                ('source_key', models.CharField(choices=[('investing', 'Investing'), ('tradingview', 'TradingView')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='macro_macro_active_fc02d7_idx'), models.Index(fields=['source_key'], name='macro_macro_source__e6ddb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MacroScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField(unique=True)),
                ('total_score', models.IntegerField()),
                ('variation_sum', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-measurement_time'],
                'indexes': [models.Index(fields=['measurement_time'], name='macro_macro_measure_d08d86_idx')],
            },
        ),
        migrations.CreateModel(
            name='MacroVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField(db_index=True)),
                ('variation_text', models.CharField(blank=True, max_length=50, null=True)),
                ('variation_decimal', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('block_reason', models.CharField(blank=True, max_length=120)),
                ('source_excerpt', models.TextField(blank=True)),
                ('market_phase', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='macro.macroasset')),
            ],
            options={
                'ordering': ['-measurement_time', 'asset__name'],
                'indexes': [models.Index(fields=['measurement_time'], name='macro_macro_measure_f3ff7c_idx'), models.Index(fields=['status'], name='macro_macro_status_effacb_idx')],
                'unique_together': {('asset', 'measurement_time')},
            },
        ),
    ]
