# Generated by Django 5.2.9 on 2026-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrovariation',
            name='payload_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
