# Generated by Django 5.2.17 on 2026-08-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0002_macrovariation_payload_bytes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='macrovariation',
            index=models.Index(fields=['asset', '-measurement_time'], name='macrovar_asset_time_idx'),
        ),
    ]
